from typing import Any

def connect_local(*args: Any, **kwargs: Any) -> Any: ...
def connect_remote(*args: Any, **kwargs: Any) -> Any: ...
def _roundtrip(value: Any) -> Any: ...
def _storage_backends() -> list[str]: ...
