[package]
name = "corium-store-abi"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
description = "Stable ABI contract for Corium storage plugins"

[dependencies]
abi_stable = "0.11.3"
async-ffi = { version = "0.5.0", features = ["abi_stable"] }
