[package]
name = "corium-db"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
description = "Immutable database values"

[dependencies]
corium-core = { workspace = true }
blake3 = "1"
corium-crypt = { workspace = true }
rpds = { workspace = true }
thiserror = "2"

[lints]
workspace = true
