//! Saga lifecycle over a peer connection (ADR-0023).
//!
//! Opening, extending, reserving, aborting, and expiring a saga are ordinary
//! transactions against the parent database, so everything in this module is
//! a transaction-data builder plus a thin [`Connection`] method that submits
//! it. There is no saga RPC and no registration: a caller who would rather
//! write the forms out longhand — or transact them from a completely
//! different client — gets exactly the same registry entry, and readers watch
//! the transitions arrive in the tx-report stream like any other data.
//!
//! Reading is likewise just reading. The registry is data in the database
//! this connection already folds locally, so [`corium_db::saga`] over
//! [`Connection::db`] (or [`Connection::sync`], for a caller that wants the
//! newest basis) answers "what is in flight?" without any help from here.
//!
//! What this module does add is the shape of a *correct* transition: the
//! forms name the saga by lookup ref, so they are idempotent under retry and
//! never depend on an entity id the caller had to remember, and each method
//! checks the saga's local state first so an ordinary mistake — aborting a
//! committed saga, extending one that expired — is reported as itself rather
//! than as a validation error about registry attributes. The transactor
//! re-checks all of it under the single-writer path regardless
//! (`corium_tx::saga`); these checks are for the caller, not for safety.
//!
//! Branches are here: [`Connection::saga_branch`] opens a second connection
//! to the saga's overlay database, which is where steps are transacted and
//! where a tier-2 reader queries partial progress. It is an ordinary
//! [`Connection`] because a branch is an ordinary database value — the whole
//! read surface applies, and nothing about reading one registers with, locks,
//! or otherwise affects the saga.
//!
//! Commit is the one transition that is *not* a transaction a client could
//! have written: [`Connection::saga_commit`] asks the transactor to merge, and
//! the transactor composes the transaction itself. It has to. The merge
//! carries the branch's whole net effect, ids from the block the parent leased
//! this saga, and the flip to `:committed`, and those three only make sense
//! together — the scan that admits them runs inside the single-writer path
//! against a value no client can hold still. So the request carries what only
//! the owner knows (guards and resolutions), and the answer is either the
//! merge or the report explaining why not.

use corium_core::{EntityId, Keyword};
use corium_db::saga::{self, Compensation, SagaEntry, SagaStatus};
use corium_db::{Db, bootstrap};
use corium_protocol::codec;
use corium_protocol::pb;
use corium_query::edn::Edn;

use crate::{Connection, PeerError, TxResult};

/// The tempid the opening transaction gives the saga entity.
const SAGA_TEMPID: &str = "corium.saga";

/// The tempid a fresh compensation-ledger entry is attached under.
const COMPENSATION_TEMPID: &str = "corium.saga.compensation";

/// What a saga is opened with.
///
/// The mandatory fields are the ones a registry entry is meaningless
/// without: the deadline, because expiry is what stops an abandoned saga from
/// pinning `t₀`-era segments forever, and the owner, because expiry-time
/// compensation runs authorized as whoever opened the saga. The owner is
/// declared by the caller today; the authorization work in ADR-0023 is where
/// the transactor starts stamping the authenticated principal itself.
#[derive(Clone, Debug)]
pub struct SagaOptions {
    /// The saga's id. Generated by [`new_saga_id`] when absent.
    pub id: Option<u128>,
    /// Human-readable purpose.
    pub description: Option<String>,
    /// Principal opening the saga.
    pub owner: String,
    /// Deadline, in milliseconds since the Unix epoch.
    pub expires_at: i64,
    /// Advisory declared touch-set — entities, or attribute entities naming
    /// whole attributes. Readers may warn on it; nothing enforces it.
    pub footprint: Vec<EntityId>,
    /// Checked reservation set, which binds the saga's own writes.
    pub reserves: Vec<EntityId>,
    /// Fixes the reservation set at open, so it can never grow.
    pub sealed: bool,
    /// Static compensating transaction data (EDN), applied atomically with a
    /// later abort or expiry.
    pub on_abort_tx: Option<String>,
    /// A `:db/fn` entity invoked as the compensating transaction instead.
    pub on_abort_fn: Option<EntityId>,
    /// Milliseconds this saga's branch is kept after it finishes, overriding
    /// the database's retention policy.
    pub retain_for: Option<i64>,
}

impl SagaOptions {
    /// Options for a saga owned by `owner` and due at `expires_at`.
    #[must_use]
    pub fn new(owner: impl Into<String>, expires_at: i64) -> Self {
        Self {
            id: None,
            description: None,
            owner: owner.into(),
            expires_at,
            footprint: Vec::new(),
            reserves: Vec::new(),
            sealed: false,
            on_abort_tx: None,
            on_abort_fn: None,
            retain_for: None,
        }
    }

    /// Opens under a caller-chosen id, rather than a generated one.
    #[must_use]
    pub fn with_id(mut self, id: u128) -> Self {
        self.id = Some(id);
        self
    }

    /// Records what the saga is for.
    #[must_use]
    pub fn describing(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Declares an advisory footprint.
    #[must_use]
    pub fn declaring(mut self, footprint: impl IntoIterator<Item = EntityId>) -> Self {
        self.footprint.extend(footprint);
        self
    }

    /// Reserves the pre-existing entities (or attributes) the saga operates
    /// on.
    #[must_use]
    pub fn reserving(mut self, reserves: impl IntoIterator<Item = EntityId>) -> Self {
        self.reserves.extend(reserves);
        self
    }

    /// Seals the reservation set at open.
    #[must_use]
    pub fn sealed(mut self) -> Self {
        self.sealed = true;
        self
    }

    /// Registers static compensating transaction data.
    #[must_use]
    pub fn compensating_with(mut self, tx_data: impl Into<String>) -> Self {
        self.on_abort_tx = Some(tx_data.into());
        self
    }

    /// Registers a `:db/fn` entity as the compensating transaction.
    #[must_use]
    pub fn compensating_by(mut self, db_fn: EntityId) -> Self {
        self.on_abort_fn = Some(db_fn);
        self
    }

    /// Keeps this saga's branch `millis` past the transition that finishes
    /// it, instead of for the database's default retention.
    ///
    /// The window is what a returning owner salvages an expired saga from and
    /// what an auditor reads the step grain of a committed one in, so a
    /// workload whose audit or salvage needs differ from the database's says
    /// so here. Zero asks for the branch to go as soon as the saga finishes.
    #[must_use]
    pub fn retaining_for(mut self, millis: i64) -> Self {
        self.retain_for = Some(millis);
        self
    }
}

/// One external-compensation ledger entry, as the orchestrator records it.
///
/// The engine never executes these. They are the orchestrator's own durable
/// notes about reverse progress it performed outside the database, keyed so a
/// resumed orchestrator can tell what it has already undone.
#[derive(Clone, Debug, Default)]
pub struct CompensationRecord {
    /// Application key naming the external effect.
    pub key: String,
    /// Orchestrator-defined status keyword.
    pub status: Option<Keyword>,
    /// Free-form detail.
    pub detail: Option<String>,
    /// When it finished, in milliseconds since the Unix epoch.
    pub completed_at: Option<i64>,
    /// Why it failed.
    pub error: Option<String>,
}

impl CompensationRecord {
    /// A ledger entry for `key`.
    #[must_use]
    pub fn new(key: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            ..Self::default()
        }
    }

    /// Sets the orchestrator's status keyword.
    #[must_use]
    pub fn with_status(mut self, status: Keyword) -> Self {
        self.status = Some(status);
        self
    }

    /// Sets the free-form detail.
    #[must_use]
    pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
        self.detail = Some(detail.into());
        self
    }

    /// Marks the compensation finished at `completed_at`.
    #[must_use]
    pub fn completed_at(mut self, completed_at: i64) -> Self {
        self.completed_at = Some(completed_at);
        self
    }

    /// Records why the compensation failed.
    #[must_use]
    pub fn failed_with(mut self, error: impl Into<String>) -> Self {
        self.error = Some(error.into());
        self
    }
}

/// A fresh random saga id (an RFC 9562 version 4 UUID).
///
/// # Errors
/// Returns [`PeerError::Saga`] when the system has no randomness to offer,
/// which is the one condition under which minting an id must fail loudly
/// rather than produce a guessable one.
pub fn new_saga_id() -> Result<u128, PeerError> {
    let mut bytes = [0_u8; 16];
    getrandom::fill(&mut bytes)
        .map_err(|error| PeerError::Saga(format!("no randomness for a saga id: {error}")))?;
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    Ok(u128::from_be_bytes(bytes))
}

/// Renders a saga id the way every corium surface spells one: 32 lowercase
/// hex digits, no dashes.
#[must_use]
pub fn format_saga_id(id: u128) -> String {
    saga::format_id(id)
}

/// Parses a saga id, with or without the conventional dashes.
#[must_use]
pub fn parse_saga_id(text: &str) -> Option<u128> {
    saga::parse_id(text)
}

fn uuid_value(id: u128) -> Edn {
    Edn::Tagged("uuid".into(), Box::new(Edn::Str(format_saga_id(id))))
}

fn instant_value(millis: i64) -> Edn {
    Edn::Tagged("inst".into(), Box::new(Edn::Long(millis)))
}

fn entity_value(entity: EntityId) -> Edn {
    Edn::Tagged(
        "eid".into(),
        Box::new(Edn::Long(i64::try_from(entity.raw()).unwrap_or(i64::MAX))),
    )
}

/// The lookup ref naming a saga: `[:db.saga/id #uuid "…"]`.
///
/// Every transition names the saga this way rather than by entity id, so the
/// forms are the same whoever builds them and a retry after an ambiguous
/// failure resolves to the same entity.
#[must_use]
pub fn saga_ref(id: u128) -> Edn {
    Edn::Vector(vec![Edn::keyword("db.saga/id"), uuid_value(id)])
}

fn add(entity: Edn, attribute: &str, value: Edn) -> Edn {
    Edn::Vector(vec![
        Edn::keyword("db/add"),
        entity,
        Edn::keyword(attribute),
        value,
    ])
}

/// Transaction data opening `id` at parent basis `basis_t`.
///
/// `basis_t` is the basis the caller observed, which is the basis the saga's
/// branch will be rooted at. The opening transaction necessarily commits at
/// some later `t`; rooting at the observed basis rather than the commit's own
/// is the conservative direction, since it only widens the range a future
/// merge scans for conflicts.
#[must_use]
pub fn open_forms(id: u128, basis_t: i64, options: &SagaOptions) -> Vec<Edn> {
    let saga = || Edn::Str(SAGA_TEMPID.into());
    let mut forms = vec![
        add(saga(), "db.saga/id", uuid_value(id)),
        add(
            saga(),
            "db.saga/status",
            Edn::Keyword(SagaStatus::Open.keyword()),
        ),
        add(saga(), "db.saga/basis-t", Edn::Long(basis_t)),
        add(saga(), "db.saga/owner", Edn::Str(options.owner.clone())),
        add(
            saga(),
            "db.saga/expires-at",
            instant_value(options.expires_at),
        ),
    ];
    if let Some(description) = &options.description {
        forms.push(add(
            saga(),
            "db.saga/description",
            Edn::Str(description.clone()),
        ));
    }
    for entity in &options.footprint {
        forms.push(add(saga(), "db.saga/footprint", entity_value(*entity)));
    }
    for entity in &options.reserves {
        forms.push(add(saga(), "db.saga/reserves", entity_value(*entity)));
    }
    if options.sealed {
        forms.push(add(saga(), "db.saga/sealed", Edn::Bool(true)));
    }
    if let Some(tx_data) = &options.on_abort_tx {
        forms.push(add(
            saga(),
            "db.saga/on-abort-tx",
            Edn::Str(tx_data.clone()),
        ));
    }
    if let Some(db_fn) = options.on_abort_fn {
        forms.push(add(saga(), "db.saga/on-abort-fn", entity_value(db_fn)));
    }
    if let Some(millis) = options.retain_for {
        forms.push(add(saga(), "db.saga/retain-for", Edn::Long(millis)));
    }
    forms
}

/// Transaction data moving `id`'s deadline to `expires_at`.
#[must_use]
pub fn extend_forms(id: u128, expires_at: i64) -> Vec<Edn> {
    vec![add(
        saga_ref(id),
        "db.saga/expires-at",
        instant_value(expires_at),
    )]
}

/// Transaction data widening `id`'s reservation set.
#[must_use]
pub fn reserve_forms(id: u128, entities: impl IntoIterator<Item = EntityId>) -> Vec<Edn> {
    entities
        .into_iter()
        .map(|entity| add(saga_ref(id), "db.saga/reserves", entity_value(entity)))
        .collect()
}

/// Transaction data finishing `id` in `status`, carrying `also` in the same
/// transaction.
///
/// The flip and whatever rides with it — a compensating transaction's data,
/// the reason an expiry could not apply one — are one append or neither,
/// which is what makes the transition atomic with its consequences.
#[must_use]
pub fn finish_forms(id: u128, status: &SagaStatus, also: Vec<Edn>) -> Vec<Edn> {
    let mut forms = vec![add(
        saga_ref(id),
        "db.saga/status",
        Edn::Keyword(status.keyword()),
    )];
    forms.extend(also);
    forms
}

/// Transaction data recording `record` in `saga`'s compensation ledger.
///
/// An entry with the same key is updated in place, so an orchestrator that
/// retries a compensation does not accumulate one ledger row per attempt.
#[must_use]
pub fn compensation_forms(saga: &SagaEntry, record: &CompensationRecord) -> Vec<Edn> {
    let existing = saga
        .compensations
        .iter()
        .find(|entry| entry.key.as_deref() == Some(record.key.as_str()))
        .map(|entry| entry.entity);
    let entry = || match existing {
        Some(entity) => entity_value(entity),
        None => Edn::Str(COMPENSATION_TEMPID.into()),
    };
    let mut forms = Vec::new();
    if existing.is_none() {
        forms.push(add(
            entity_value(saga.entity),
            "db.saga/compensations",
            entry(),
        ));
        forms.push(add(
            entry(),
            "db.saga.compensation/key",
            Edn::Str(record.key.clone()),
        ));
    }
    if let Some(status) = &record.status {
        forms.push(add(
            entry(),
            "db.saga.compensation/status",
            Edn::Keyword(status.clone()),
        ));
    }
    if let Some(detail) = &record.detail {
        forms.push(add(
            entry(),
            "db.saga.compensation/detail",
            Edn::Str(detail.clone()),
        ));
    }
    if let Some(completed_at) = record.completed_at {
        forms.push(add(
            entry(),
            "db.saga.compensation/completed-at",
            instant_value(completed_at),
        ));
    }
    if let Some(error) = &record.error {
        forms.push(add(
            entry(),
            "db.saga.compensation/error",
            Edn::Str(error.clone()),
        ));
    }
    forms
}

/// What one merge attempt came to.
///
/// A refused merge is an ordinary answer, not an error: the parent moved, the
/// report says how, and the saga is still open with its branch intact. Only
/// something that makes the question unanswerable — an unknown saga, novelty
/// the parent's current schema rejects — comes back as a [`PeerError`].
#[derive(Clone, Debug)]
pub enum MergeOutcome {
    /// The branch merged, as one parent transaction.
    Committed(MergeReport),
    /// The parent has drifted, or a declared guard no longer holds.
    Conflict(ConflictReport),
}

impl MergeOutcome {
    /// The merge, if it happened.
    #[must_use]
    pub const fn merged(&self) -> Option<&MergeReport> {
        match self {
            Self::Committed(report) => Some(report),
            Self::Conflict(_) => None,
        }
    }

    /// The conflict report, if the merge was refused.
    #[must_use]
    pub const fn conflict(&self) -> Option<&ConflictReport> {
        match self {
            Self::Conflict(report) => Some(report),
            Self::Committed(_) => None,
        }
    }
}

/// What a merge that landed did.
#[derive(Clone, Debug)]
pub struct MergeReport {
    /// The parent's basis before the merge.
    pub basis_before: u64,
    /// The merge transaction's `t` — the single basis at which every one of
    /// the saga's effects became canonical.
    pub basis_t: u64,
    /// The merge transaction's `:db/txInstant`.
    pub tx_instant: i64,
    /// Branch transactions squashed into it.
    pub steps: u64,
    /// Net datoms it applied. Zero when a retry found the saga already
    /// committed — that answer comes from the registry, which records the
    /// merge transaction and the step count but not the datom count.
    pub datoms: u64,
}

/// Why a merge was refused, as the registry now records it.
///
/// `report` is the EDN the transactor also wrote to
/// `:db.saga/conflict-report`, so a process that was not the one asking can
/// read the same document out of the registry.
#[derive(Clone, Debug)]
pub struct ConflictReport {
    /// The parent's basis after the report was recorded.
    pub basis_t: u64,
    /// Branch transactions the merge would have squashed.
    pub steps: u64,
    /// Net datoms it would have applied.
    pub datoms: u64,
    /// The EDN report: each colliding unit with both sides' values.
    pub report: String,
}

/// A connection to a saga's branch: where its steps run and what a tier-2
/// reader reads (ADR-0023).
///
/// The branch is a database, and this is a `Connection` to it — so the whole
/// read surface (Datalog, Pull, SQL, `as-of`, `since`, `history`) applies to
/// [`SagaBranch::db`] with nothing new to learn, and a step is an ordinary
/// transaction. What the wrapper adds is vocabulary: a *step* is a
/// transaction against the branch, and everything read here is provisional
/// under this saga id until the parent's registry says `:committed`.
///
/// Reading a branch registers nothing, locks nothing, and has no effect on
/// the saga. A reader who never asks for one is unaffected by every saga in
/// flight.
pub struct SagaBranch {
    connection: Connection,
    saga: u128,
    basis_t: u64,
}

impl std::fmt::Debug for SagaBranch {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("SagaBranch")
            .field("saga", &format_saga_id(self.saga))
            .field("db", &self.connection.db_name())
            .field("basis_t", &self.basis_t)
            .finish()
    }
}

impl SagaBranch {
    /// The saga this branch belongs to.
    #[must_use]
    pub const fn saga_id(&self) -> u128 {
        self.saga
    }

    /// The parent basis `t₀` the branch is rooted at.
    ///
    /// Below it the branch answers exactly what the parent answers, because
    /// it is the same history; above it, the branch's own steps.
    #[must_use]
    pub const fn basis_t(&self) -> u64 {
        self.basis_t
    }

    /// The branch's current value, without waiting on the transactor.
    #[must_use]
    pub fn db(&self) -> Db {
        self.connection.db()
    }

    /// The branch's value at the newest basis this connection can reach.
    ///
    /// # Errors
    /// Returns [`PeerError`] when the sync fails.
    pub async fn sync(&self) -> Result<Db, PeerError> {
        self.connection.sync().await
    }

    /// The connection underneath, for everything a connection does.
    #[must_use]
    pub const fn connection(&self) -> &Connection {
        &self.connection
    }

    /// Transacts one step against the branch.
    ///
    /// A step is an ordinary transaction — tempids, upsert, `:db/cas`,
    /// database functions, tx metadata — validated against the branch and
    /// durable in its log before this returns. It is refused if it would
    /// break the saga's declaration: allocations come from the leased id
    /// blocks, and a reserved saga writes and references only what it
    /// reserved.
    ///
    /// # Errors
    /// Returns [`PeerError`] for a rejected step or transport failure. A saga
    /// that has already finished refuses steps, which is the error a caller
    /// resuming stale work will see.
    pub async fn step(&self, forms: Vec<Edn>) -> Result<TxResult, PeerError> {
        self.connection.transact(forms).await
    }

    /// The branch's own transactions: one record per step, in order.
    ///
    /// The parent's history below `t₀` is deliberately excluded — it is the
    /// parent's, and this is the step grain the design promises auditors.
    #[must_use]
    pub fn steps(&self) -> Vec<corium_log::TxRecord> {
        self.connection.tx_range(self.basis_t + 1, None)
    }
}

/// What a completed lifecycle transition leaves behind.
#[derive(Clone, Debug)]
pub struct SagaResult {
    /// The registry entry as of the transaction that changed it.
    pub entry: SagaEntry,
    /// The transaction itself.
    pub tx: TxResult,
}

/// What ending a saga — aborting or expiring it — left behind.
///
/// It is not a [`SagaResult`] because the transaction is composed in the
/// transactor rather than here, so there is no tempid map to report: what
/// there is instead is whether the compensation landed, which is the question
/// an orchestrator asks next.
#[derive(Clone, Debug)]
pub struct FinishResult {
    /// The registry entry as of the transition.
    pub entry: SagaEntry,
    /// Parent basis before the transition.
    pub basis_before: u64,
    /// The transition's `t`.
    pub basis_t: u64,
    /// The transition's `:db/txInstant`.
    pub tx_instant: i64,
    /// Whether compensation datoms landed in the same transaction.
    pub compensated: bool,
    /// Why a registered compensation did not land, when one did not. Also in
    /// `:db.saga/on-abort-error`, where it outlives this call.
    pub on_abort_error: Option<String>,
}

impl Connection {
    /// Opens a saga, returning its registry entry.
    ///
    /// The saga is rooted at the basis this call syncs to, and an id is
    /// minted when the options do not name one.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the id is already in the registry —
    /// a saga id names one saga for the life of the database — and otherwise
    /// whatever the transaction fails with.
    pub async fn saga_open(&self, options: &SagaOptions) -> Result<SagaResult, PeerError> {
        let db = self.sync().await?;
        let id = match options.id {
            Some(id) => id,
            None => new_saga_id()?,
        };
        if saga::entry(&db, id).is_some() {
            return Err(PeerError::Saga(format!(
                "saga {} is already in the registry",
                format_saga_id(id)
            )));
        }
        let basis_t = i64::try_from(db.basis_t()).unwrap_or(i64::MAX);
        let tx = self.transact(open_forms(id, basis_t, options)).await?;
        finished(id, tx)
    }

    /// Extends an open saga's deadline.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the saga is unknown or no longer
    /// open, and otherwise whatever the transaction fails with.
    pub async fn saga_extend(&self, id: u128, expires_at: i64) -> Result<SagaResult, PeerError> {
        self.expect_open(id, "extend").await?;
        let tx = self.transact(extend_forms(id, expires_at)).await?;
        finished(id, tx)
    }

    /// Adds entities (or attributes) to an unsealed saga's reservation set.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the saga is unknown, no longer open,
    /// or sealed, and otherwise whatever the transaction fails with.
    pub async fn saga_reserve(
        &self,
        id: u128,
        entities: impl IntoIterator<Item = EntityId> + Send,
    ) -> Result<SagaResult, PeerError> {
        let entry = self.expect_open(id, "reserve for").await?;
        if entry.sealed {
            return Err(PeerError::Saga(format!(
                "saga {} is sealed; its reservation set was fixed at open",
                format_saga_id(id)
            )));
        }
        let tx = self.transact(reserve_forms(id, entities)).await?;
        finished(id, tx)
    }

    /// Aborts an open saga, applying whatever compensation it registered at
    /// open.
    ///
    /// With no registered compensation this is the design's default abort and
    /// leaves no trace in canonical state: one status transaction, the branch
    /// retained through its window and then discarded, nothing else.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the saga is unknown or already
    /// finished, and otherwise whatever the transaction fails with — a
    /// registered compensation that does not validate fails the abort and
    /// leaves the saga open, which is the point of applying it in the same
    /// transaction.
    pub async fn saga_abort(&self, id: u128) -> Result<FinishResult, PeerError> {
        self.saga_finish(id, &SagaStatus::Aborted, None).await
    }

    /// Aborts an open saga, applying `compensation` in the same transaction
    /// *instead of* whatever it registered at open.
    ///
    /// The compensating transaction is fresh transaction data, validated like
    /// any other and landing atomically with the flip: a deliberately
    /// authored failure record, never a partial landing of saga novelty. An
    /// empty vector means "abort with nothing", which is how a caller
    /// deliberately drops a registered compensation.
    ///
    /// # Errors
    /// As [`Connection::saga_abort`].
    pub async fn saga_abort_with(
        &self,
        id: u128,
        compensation: Vec<Edn>,
    ) -> Result<FinishResult, PeerError> {
        self.saga_finish(id, &SagaStatus::Aborted, Some(compensation))
            .await
    }

    /// Expires an open saga, applying whatever compensation it registered.
    ///
    /// This is the transition the expiry sweep performs, exposed because an
    /// operator sometimes has to perform it by hand — a saga whose owner is
    /// known not to be coming back should not have to wait out its deadline.
    /// It is distinct from an abort so that a returning owner can tell "the
    /// system ended this" from "I ended this", whoever wrote the transition.
    ///
    /// Unlike an abort, a compensation that does not validate does not fail
    /// this: liveness outranks, so the saga expires without it and the reason
    /// lands in `:db.saga/on-abort-error`, which the result also carries.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the saga is unknown or already
    /// finished, and otherwise whatever the transaction fails with.
    pub async fn saga_expire(&self, id: u128) -> Result<FinishResult, PeerError> {
        self.saga_finish(id, &SagaStatus::Expired, None).await
    }

    /// Ends an open saga, composing the flip and its compensation in the
    /// transactor.
    ///
    /// The flip alone is ordinary transaction data — [`finish_forms`] builds
    /// it, and a client that wants no compensation may transact it directly.
    /// What is here instead of there is a *registered* compensation: a
    /// `:db.saga/on-abort-fn` is invoked with the parent's current value and
    /// the branch value, and no client holds the second one.
    async fn saga_finish(
        &self,
        id: u128,
        status: &SagaStatus,
        compensation: Option<Vec<Edn>>,
    ) -> Result<FinishResult, PeerError> {
        self.expect_open(
            id,
            if matches!(status, SagaStatus::Expired) {
                "expire"
            } else {
                "abort"
            },
        )
        .await?;
        let replace = compensation.is_some();
        let response = self
            .saga_finish_raw(pb::SagaFinishRequest {
                db: self.db_name().to_owned(),
                protocol_version: corium_protocol::PROTOCOL_VERSION,
                saga: format_saga_id(id),
                status: status.name().to_owned(),
                compensation: codec::encode_edn(&Edn::Vector(compensation.unwrap_or_default())),
                replace_compensation: replace,
            })
            .await?;
        // The transition is in the parent's log: catch this connection up so
        // the entry below is the one the transaction left behind.
        self.sync_to(response.basis_t).await?;
        Ok(FinishResult {
            entry: entry_of(&self.db(), id)?,
            basis_before: response.basis_before,
            basis_t: response.basis_t,
            tx_instant: response.tx_instant,
            compensated: response.compensated,
            on_abort_error: Some(response.on_abort_error).filter(|error| !error.is_empty()),
        })
    }

    /// Commits a saga: merges its branch into the parent as one transaction.
    ///
    /// `guards` are read dependencies to check against the parent's current
    /// value, beyond whatever the branch's steps declared as `:db.saga/guard`
    /// metadata along the way; the transactor evaluates the union. A guard is
    /// either `[:db/cas <entity> <attribute> <value>]` — the compare half of a
    /// compare-and-swap, with `nil` for "holds nothing" — or
    /// `{:guard <query>}`, a Datalog query that must return a row (add
    /// `:expect :none` for one that must not).
    ///
    /// `resolutions` answer a previous attempt's conflict report, each fenced
    /// to the parent-side value that report showed:
    /// `{:e <entity> :a <attribute> :parent <value> :take :parent}` drops the
    /// branch's write, and `:take :branch` overrides — which only a
    /// write–write conflict on a cardinality-one pair admits. Drift beyond the
    /// resolved set is a fresh conflict, never silently absorbed, so a stale
    /// resolution refuses the merge rather than quietly applying.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the saga is unknown or has already
    /// aborted or expired, and otherwise whatever the merge fails with. A
    /// merge the parent refuses is [`MergeOutcome::Conflict`], not an error.
    pub async fn saga_commit(
        &self,
        id: u128,
        guards: Vec<Edn>,
        resolutions: Vec<Edn>,
    ) -> Result<MergeOutcome, PeerError> {
        let entry = entry_of(&self.sync().await?, id)?;
        // An already-committed saga is not an error: the transactor answers a
        // retry with the merge it finds, which is what makes a commit whose
        // acknowledgement was lost safe to repeat.
        if let Some(status @ (SagaStatus::Aborted | SagaStatus::Expired)) = &entry.status {
            return Err(PeerError::Saga(format!(
                "cannot commit saga {}: it is {status}",
                format_saga_id(id)
            )));
        }
        let response = self
            .saga_commit_raw(pb::SagaCommitRequest {
                db: self.db_name().to_owned(),
                protocol_version: corium_protocol::PROTOCOL_VERSION,
                saga: format_saga_id(id),
                guards: codec::encode_edn(&Edn::Vector(guards)),
                resolutions: codec::encode_edn(&Edn::Vector(resolutions)),
            })
            .await?;
        // Whatever happened, it happened in the parent's log: catch this
        // connection up so the caller reads a value that includes it.
        self.sync_to(response.basis_t).await?;
        if response.committed {
            return Ok(MergeOutcome::Committed(MergeReport {
                basis_before: response.basis_before,
                basis_t: response.basis_t,
                tx_instant: response.tx_instant,
                steps: response.steps,
                datoms: response.datoms,
            }));
        }
        let report = match codec::decode_edn(&response.conflict_report)? {
            Edn::Str(report) => report,
            other => other.to_string(),
        };
        Ok(MergeOutcome::Conflict(ConflictReport {
            basis_t: response.basis_t,
            steps: response.steps,
            datoms: response.datoms,
            report,
        }))
    }

    /// Records an external-compensation ledger entry.
    ///
    /// The ledger is the one part of a saga that keeps being written after it
    /// finishes: reverse progress outside the database outlives the branch,
    /// and an orchestrator resumes from it.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the saga is unknown, and otherwise
    /// whatever the transaction fails with.
    pub async fn saga_compensate(
        &self,
        id: u128,
        record: &CompensationRecord,
    ) -> Result<SagaResult, PeerError> {
        let db = self.sync().await?;
        let entry = entry_of(&db, id)?;
        let tx = self.transact(compensation_forms(&entry, record)).await?;
        finished(id, tx)
    }

    /// Connects to the branch of saga `id` — the tier-2 read surface, and
    /// where steps are transacted.
    ///
    /// The branch is served over the ordinary database machinery under a name
    /// derived from the saga id, so this is a second [`Connection`] with this
    /// one's endpoints, credentials, and keys. The saga is looked up here
    /// first so "there is no such saga" is reported as itself rather than as a
    /// failure to reach a database nobody named.
    ///
    /// A *finished* saga's branch still opens, for as long as retention keeps
    /// it. That is the whole point of the retention window: a committed
    /// saga's branch holds the step grain its single squashed parent commit
    /// does not, and an aborted or expired one is the record of what the
    /// workflow did outside the database and must now unwind. Either is
    /// read-only in the only way that matters — the transactor refuses steps
    /// the moment the saga is no longer open — and either is gone once the
    /// sweep has discarded it, which is reported as itself.
    ///
    /// # Errors
    /// Returns [`PeerError::Saga`] when the saga is unknown or its entry
    /// carries no opening basis; otherwise whatever the connection fails
    /// with, which for a finished saga includes retention having discarded
    /// the branch.
    pub async fn saga_branch(&self, id: u128) -> Result<SagaBranch, PeerError> {
        let entry = entry_of(&self.sync().await?, id)?;
        let basis_t = entry
            .basis_t
            .and_then(|basis| u64::try_from(basis).ok())
            .ok_or_else(|| {
                PeerError::Saga(format!(
                    "saga {} has no opening basis; it has no branch",
                    format_saga_id(id)
                ))
            })?;
        let connection = Self::connect(self.config().for_saga(id)).await?;
        Ok(SagaBranch {
            connection,
            saga: id,
            basis_t,
        })
    }

    /// The registry entry for `id` at the newest basis this connection can
    /// reach.
    ///
    /// # Errors
    /// Returns [`PeerError`] when the sync fails. A saga this database does
    /// not have is `Ok(None)`, not an error: asking about an unknown saga is
    /// a legitimate question with an answer.
    pub async fn saga(&self, id: u128) -> Result<Option<SagaEntry>, PeerError> {
        Ok(saga::entry(&self.sync().await?, id))
    }

    /// Every registry entry at the newest basis this connection can reach.
    ///
    /// # Errors
    /// Returns [`PeerError`] when the sync fails.
    pub async fn sagas(&self) -> Result<Vec<SagaEntry>, PeerError> {
        Ok(saga::entries(&self.sync().await?))
    }

    async fn expect_open(&self, id: u128, action: &str) -> Result<SagaEntry, PeerError> {
        let entry = entry_of(&self.sync().await?, id)?;
        match &entry.status {
            Some(SagaStatus::Open) => Ok(entry),
            Some(status) => Err(PeerError::Saga(format!(
                "cannot {action} saga {}: it is {status}",
                format_saga_id(id)
            ))),
            None => Err(PeerError::Saga(format!(
                "cannot {action} saga {}: its registry entry has no status",
                format_saga_id(id)
            ))),
        }
    }
}

fn entry_of(db: &Db, id: u128) -> Result<SagaEntry, PeerError> {
    saga::entry(db, id).ok_or_else(|| {
        PeerError::Saga(format!(
            "no saga {} in this database's registry",
            format_saga_id(id)
        ))
    })
}

fn finished(id: u128, tx: TxResult) -> Result<SagaResult, PeerError> {
    let entry = entry_of(&tx.db_after, id)?;
    Ok(SagaResult { entry, tx })
}

/// The ledger entry for `key`, if the saga has one.
#[must_use]
pub fn compensation_for<'a>(saga: &'a SagaEntry, key: &str) -> Option<&'a Compensation> {
    saga.compensations
        .iter()
        .find(|entry| entry.key.as_deref() == Some(key))
}

/// Whether `db` knows the saga vocabulary at all.
///
/// A database created before the registry existed carries no `:db.saga/*`
/// attributes, and every saga surface should say so plainly rather than
/// reporting an empty registry.
#[must_use]
pub fn registry_installed(db: &Db) -> bool {
    db.schema().get(bootstrap::SAGA_ID).is_some()
}
